gleam_tool := justfile_directory() / "../../target/debug/gleam"

transpile:
	cargo build
	{{ gleam_tool }} compile-package \
		--package {{ justfile_directory() }}/playground \
		--lib {{ justfile_directory() }}/lib \
		--out {{ justfile_directory() }}/output \
		--target native

watch:
	watchexec --exts rs,gleam \
		--watch {{ justfile_directory() }} \
		--clear \
		--on-busy-update=restart \
		-- just transpile

compile:
	clang++ -Wall -std=c++17 \
		-I output/dist/ \
		-fPIC \
		output/dist/hello_world.cc \
		-o hello_world.o
